---
all:
  children:
    macos:
      hosts:
        mac-studio-01::
          ansible_host: 192.168.13.155
          ansible_user: ctrlh
          # Use key-based SSH when possible. For password auth, uncomment:
          # ansible_password: "{{ vault_macos_ssh_password }}"
    linux:
      hosts:
#        ubuntu-dev-01:
#          ansible_host: 192.168.1.20
#          ansible_user: ansible
          # Use key-based SSH when possible. For password auth, uncomment:
          # ansible_password: "{{ vault_linux_ssh_password }}"
    windows:
      hosts:
#        win11-workstation-01:
#          ansible_host: 192.168.1.30
#          ansible_user: Administrator
#          ansible_password: "{{ vault_windows_admin_password }}"
#          ansible_connection: winrm
#          ansible_winrm_transport: ntlm
#          ansible_port: 5985
#          ansible_winrm_server_cert_validation: ignore
