---
- name: Manage macOS workstations
  hosts: macos
  gather_facts: true
  roles:
    - macos

- name: Manage Linux workstations
  hosts: linux
  gather_facts: true
  roles:
    - linux

- name: Manage Windows workstations
  hosts: windows
  gather_facts: true
  roles:
    - windows
